//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProject
    {
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectOwner { get; set; }
        public string ProjectDetail { get; set; }
        public string ProjectImage { get; set; }
        public bool Successful { get; set; }
    }
}
